mimetype = {
    ".ttf": 'font/ttf',
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    '.eot':'application/vnd.ms-fontobject',
    ".svg": 'image/svg+xml',
    ".webp": 'image/webp',
    ".png": 'image/png' ,
    ".jpg": 'image/jpg',
    ".jpeg": 'image/jpg',
    ".jfif": 'image/jpg',
    ".jpg": 'image/jpg',
    ".jpeg": 'image/jpg',
    ".jfif": 'image/jpg',
    ".pjpeg": 'image/jpg',
    ".pjp": 'image/jpg',
    ".bmp": 'image/bmp',
    ".ico": 'image/x-icon',
    ".cur": 'image/x-icon',
    ".tiff": 'image/tiff',
    ".tif": 'image/tiff',
    ".avif": 'image/avif',
    ".gif": 'image/gif',
    ".apng": 'image/apng',
    ".js": 'application/javascript',
    ".css": 'text/css'
}